### ISSUE TITLE
Update RTMA consensus land/sea mask and terrain files for CONUS

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [AnnetteGibbs-NOAA/RTMA_consensus_surface_properties#1]
Following requests from the field, we are updating the RTMA CONUS land/sea mask and terrain around the Great Salt Lake to better match the lake's current shape. The updated files will go into HRRR smartinit, RAP smartinit, NAM smartinit, RTMA, and URMA.

George Wagner from MDL has since provided the updated land/sea mask files, which comprise the full land/sea mask, and the version that retains select large lakes only. For clarity, the full mask is used in HRRR smartinit, RAP smartinit, NAM smartinit, while the "simplified" version is used to build the background error covariances in RTMA & URMA.

This task consists of ensuring that the consensus terrain is consistent with the updated full mask. In particular, the lake elevation may have to be adjusted to be consistent with the elevation of the adjacent land points.

As he has done numerous times before, George Gayno has generously agreed to work on this task. We are now hoping that he will also be able to mentor @AnnetteGibbs-NOAA on how to use his codes and scripts for the next round of mask & terrain updates.

Location of land/sea mask and terrain files on WCOSS (venus & mars):
/gpfs/dell2/emc/modeling/noscrub/Annette.Gibbs/RTMA_consensus_surface_properties

**Comment by GeorgeGayno-NOAA** [comment]
@AnnetteGibbs-NOAA Can you add me and Manuel to your repository?  I can't assign this issue to myself.  And I would like tag Manuel to comments in issues and pull requests.

**Comment by GeorgeGayno-NOAA** [comment]
First task: 

Create a 'no lake' version of this file:

`/gpfs/dell2/emc/modeling/noscrub/Annette.Gibbs/RTMA_consensus_surface_properties/conus_landwater_v2p5_fine.gb2`

This was done on Mars using 4314d56.

**Comment by ManuelPondeca-NOAA** [comment]
I tested Georges 'no lake' version of the land/sea mask /gpfs/dell1/stmp/George.Gayno/no.lakes.for.manuel/nolakes.gb2 (mars) in the RTMA and did not find any issues. The RTMA tests contained a small caveat though. They were done with the operational  smartinit files, when when they should ideally have been done with smartnit files produced with the latest 'full' land/sea mask from Geoff Wagner. Such test smartinit files are not available, however. I am  nonetheless fairly confident that George's 'no lake' version' of the 'full' mask is good to go.

**Comment by GeorgeGayno-NOAA** [comment]
Second task:

Adjust the terrain for the new land mask.  This new mask has changes near Great Salt Lake and San Francisco Bay.

Use this mask:  /gpfs/dell2/emc/modeling/noscrub/Annette.Gibbs/RTMA_consensus_surface_properties/conus_landwater_v2p5_fine.gb2

To adjust this terrain:
/gpfs/dell2/emc/modeling/noscrub/Annette.Gibbs/RTMA_consensus_surface_properties/nam_smarttopoconus2p5.grb2

**Comment by GeorgeGayno-NOAA** [comment]
The second task was accomplished with 0a29870b on Mars. 

The output was placed here:
/gpfs/dell1/stmp/George.Gayno/coasts.save

**Comment by GeorgeGayno-NOAA** [comment]
Per @AnnetteGibbs-NOAA request, I will baseline my utilities to fix the scan mode and to reclassify the land mask categories to the standard  0-water and 1-land.
